### ISSUE TITLE
Not able to retrieve info

### ISSUE THREAD

**Issue by planbdigital-git** [01F0/flashforge-finder-api#1]
Hello, thanks for providing the code, but I am not able to retrieve the printer info. Could you please specify, where in the webapi.py you would expect the IP of the printer? AND is the flask server only available on localhost?? Thanks for some hints. Martin

**Comment by planbdigital-git** [comment]
Ok - I solved myself. Do NOT enter the IP of the printer in webapi.py as written in the documentation. Start Flask with FLASK_APP=webapi.py flask run --host=0.0.0.0 --port=5000 otherwise the server is not reachable from an external browser.

**Comment by 01F0** [comment]
Oh, nice work on solving it! I'll update the documentation. :)
