### ISSUE TITLE
Progress miscalculated as zero for FF Adventurer 3

### ISSUE THREAD

**Issue by jptrsn** [01F0/flashforge-finder-api#2]
I'm using this project with my Flashforge Adventurer 3, and it works entirely as expected.

However, the PercentageComplete doesn't calculate as I'd expect. For a fairly small print, this is what it's returning when the screen on the device shows 76%

> {"BytesPrinted":"76","BytesTotal":"100","PercentageCompleted":0}

Also, can you share any resources that helped you learn how to reverse engineered the API from the device? I'd like to figure out if I can stream the camera feed, but so far I've had no luck finding any information about the way they've implemented the device API.

**Comment by 01F0** [comment]
Interesting, so the Adventurer gives you back percentage, my Finder gives me number of bytes instead. 

Try pulling the latest version. I'm assuming you're running Python 2? Version 2/3 seem to handle casting differently so I had to add an explicit cast.

No specific resources, try Wireshark on port 8899. 

I bet they have a separate (HTTP) server for the camera feed, I don't think this API is suitable for video streams.

**Comment by 01F0** [comment]
I'm closing this one, please let me know if it didn't solve the issue and I'll open it again. 👍
